version: '3.9'

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin